version: '3.9'

services:
  web:
    image: myapp
    deploy:
      replicas: 6
      resources:
        limits: 
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
       - "8080:80"
